[[main]]
    identifier = "get_started"
    name = "GET STARTED"
    pageRef = "/get_started"
    weight = 1
[[main]]
    parent = "get_started"
    identifier = "schedule"
    name = "SCHEDULE"
    pageRef = "/get_started/schedule"
    weight = 2
[[main]]
    parent = "get_started"
    identifier = "entry"
    name = "ENTRY"
    pageRef = "/get_started/entry"
    weight = 3
[[main]]
    parent = "get_started"
    identifier = "checkin"
    name = "CHECK IN"
    pageRef = "/get_started/checkin"
    weight = 4
[[main]]
    identifier = "travel"
    name = "TRAVEL"
    pageRef = "/travel"
    weight = 10
[[main]]
    parent = "travel"
    indentifier = "sightseeing"
    name = "Sightseeing"
    pageRef = "/travel/sightseeing"
    weight = 11
[[main]]
    parent = "travel"
    indentifier = "transportation"
    name = "Transportation"
    pageRef = "/travel/transportation"
    weight = 12
[[main]]
    parent = "travel"
    indentifier = "accommodation"
    name = "Accommodation"
    pageRef = "/travel/accommodation"
    weight = 13
[[main]]
    identifier = "competitions"
    name = "COMPETITION"
    pageRef = "/competitions"
    weight = 20
[[main]]
    parent = "competitions"
    indentifier = "bulletins"
    name = "BULLETINS"
    pageRef = "/competitions/bulletins"
    weight = 21
[[main]]
    parent = "competitions"
    indentifier = "startlists"
    name = "START LIST"
    pageRef = "/competitions/startlists"
    weight = 22
[[main]]
    parent = "competitions"
    indentifier = "results"
    name = "RESULTS"
    pageRef = "/competitions/results"
    weight = 23
[[main]]
    indentifier = "JOINT EVENTS"
    name = "JOINT EVENTS"
    pageRef = "/joint_events"
    weight = 30
[[main]]
    parent = "JOINT EVENTS"
    indentifier = "preevents"
    name = "PRE EVENTS"
    pageRef = "/joint_events/pre_events"
    weight = 31
[[main]]
    parent = "JOINT EVENTS"
    indentifier = "orienteeringinjapan"
    name = "ORIENTEERING IN JAPAN"
    pageRef = "/joint_events/orienteering_in_japan"
    weight = 32
[[main]]
    indentifier = "PHOTO"
    name = "PHOTO"
    weight = 50
[[main]]
    parent = "PHOTO"
    indentifier="preevent_day1"
    name = "Pre event day 1"
    url = "https://photos.app.goo.gl/j5LMnWZgFKxrxqY69"
    weight = 51
[[main]]
    parent = "PHOTO"
    indentifier="preevent_day2"
    name = "Pre event day 2"
    url = "https://photos.app.goo.gl/d9z6y3KYyaJGhyA29"
    weight = 52