[[main]]
    identifier = "get_started"
    name = "はじめる"
    pageRef = "/get_started/"
    weight = 2
[[main]]
    parent = "get_started"
    identifier = "entry"
    name = "エントリ"
    pageRef = "/get_started/entry"
    weight = 3
[[main]]
    parent = "get_started"
    identifier = "schedule"
    name = "イベントスケジュール"
    pageRef = "/get_started/schedule"
    weight = 1
[[main]]
    identifier = "travel"
    name = "交通と宿泊"
    pageRef = "/travel/"
    weight = 10
[[main]]
    parent = "travel"
    indentifier = "transportation"
    name = "アクセス"
    pageRef = "/travel/transportation"
    weight = 11
[[main]]
    parent = "travel"
    indentifier = "accommodation"
    name = "宿泊情報"
    pageRef = "/travel/accommodation"
    weight = 12
[[main]]
    identifier = "competitions"
    name = "競技情報"
    pageRef = "/competitions"
    weight = 20
[[main]]
    parent = "competitions"
    indentifier = "bulletins"
    name = "要項"
    pageRef = "/competitions/bulletins"
    weight = 21
[[main]]
    parent = "competitions"
    indentifier = "startlists"
    name = "スタートリスト"
    pageRef = "/competitions/startlists"
    weight = 22
[[main]]
    parent = "competitions"
    indentifier = "resultlists"
    name = "競技結果"
    pageRef = "/competitions/results"
    weight = 23
[[main]]
    indentifier = "jointevents"
    name = "共催イベント"
    pageRef = "/joint_events"
    weight = 30
[[main]]
    parent = "共催イベント"
    indentifier = "preevents"
    name = "PRE EVENTS"
    pageRef = "/joint_events/pre_events"
    weight = 31
[[main]]
    parent = "共催イベント"
    indentifier = "orienteeringinjapan"
    name = "ORIENTEERING IN JAPAN"
    pageRef = "/joint_events/orienteering_in_japan"
    weight = 32
[[main]]
    indentifier = "写真"
    name = "写真"
    weight = 50
[[main]]
    parent = "写真"
    indentifier = "preeventday1"
    name = "プレイベント1日目"
    url = "https://photos.app.goo.gl/j5LMnWZgFKxrxqY69"
    weight = 51
[[main]]
    parent = "写真"
    indentifier = "preeventday2"
    name = "プレイベント2日目"
    url = "https://photos.app.goo.gl/d9z6y3KYyaJGhyA29"
    weight = 52